name: CI

on:
    push:
        tags:
            - 'v*.*.*'

permissions:
    contents: write

jobs:
    deploy:
        name: Release and deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Read .nvmrc
              run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
              id: nvm

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '${{ steps.nvm.outputs.NVMRC }}'
                  cache: 'npm'

            - name: Install Node.js dependencies
              run: npm ci

            - name: Build assets.
              run: npm run build

            - name: Zip directory
              run: |
                  pushd ${{ github.event.repository.name }}
                  zip -r ../${{ github.event.repository.name }}-${{ github.ref_name }}.zip . -x 'src/*'
                  popd

            - name: Upload zip to GitHub Release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh release create "${{ github.ref_name }}" \
                    --title "${{ github.ref_name }}" \
                    --notes "Release of version ${{ github.ref_name }}" \
                    "${{ github.event.repository.name }}-${{ github.ref_name }}.zip"

            - name: Set up SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  ssh-keyscan -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts

            - name: Upload to LightSail
              run: |
                  scp ${{ github.event.repository.name }}-${{ github.ref_name }}.zip ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:/tmp/${{ github.event.repository.name }}-${{ github.ref_name }}.zip

            - name: Deploy on server
              run: |
                  ssh ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
                    unzip -o /tmp/${{ github.event.repository.name }}-${{ github.ref_name }}.zip -d ${{ secrets.LIGHTSAIL_DIR }}
                    rm /tmp/${{ github.event.repository.name }}-${{ github.ref_name }}.zip
                  EOF
